name: rally checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - synchronize
jobs:
  check-rally-integration:
    name: check-rally-artifact
    uses: RepublicServicesRepository/dops-gha-rally-integration/.github/workflows/workflow.yml@v1.0.0
    secrets:
      github_pat: ${{ secrets.REPUBLIC_SYSTEM_RISE_PAT }}
      rally_api_key: ${{secrets.RALLY_API_KEY}}
